apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: require-app-label

spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces:
      - "default"
    # This below code is to exclude certain namespaces from this constraint, if you want to apply this constraint to all namespaces, just comment out the "namespaces" field and uncomment the "excludedNamespaces" field and add the namespaces you want to exclude.
    # excludedNamespaces:
    #   - kube-system
    #   - argocd
    #   - gatekeeper-system
    #   - vault
  parameters:
    labels:
      - "app.kubernetes.io/name"
