apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
<<<<<<< HEAD
  externalName: {{ .Values.service.externalName | default "mysql.default.svc.cluster.local" }}
=======
  externalName: mysql.default.svc.cluster.local
>>>>>>> 754ba02 (updating files according to the helm)
